version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: thop
    main: ./cmd/thop
    binary: thop
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: thop
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

nix:
  - name: thop
    ids: [thop]
    homepage: "https://github.com/rwilgaard/thop"
    description: "Fuzzy tmux session manager with frecency ranking"
    license: "mit"
    main_program: "thop"
    repository:
      owner: rwilgaard
      name: nix-packages
      branch: main
      token: "{{ .Env.NIX_PACKAGES_TOKEN }}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - Merge pull request
      - Merge branch
